# Generated by Django 4.1.3 on 2022-11-21 09:39

import ads.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='def_slug', max_length=10, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[ads.validators.birth_date]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Регистрация с домена rumbler.ru запрещена', regex='rambler.ru')], verbose_name='email address'),
        ),
    ]
